---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: staging

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    provisioner:
      client_rb:
        environment: production
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-base]"
    - "recipe[mysql::client]"
    - "recipe[rackspace-mysql-proxy]"
    - "recipe[odi-users]"
    - "recipe[lib-curl]"
    - "recipe[nodejs]"
#    - "recipe[envbuilder]"
    - "recipe[memcached]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployer]"
    data_bags_path: test/data_bags
    attributes:
      user: "certificates"
      odi-ruby:
        users:
          certificates:
          - 1.9.3-p547
      envbuilder:
        base_dir: "/home/certificates"
        base_dbi: "production"
        owner: "certificates"
        group: "certificates"
      project_fqdn: "certificates.theodi.org"
      git_project: "open-data-certificate"
      databags:
        primary: "certificates"
      deployment:
        revision: "STAGING"
        precompile_assets: false
        rack_env: production
        assets_allow_origin: "*"
      database: certificates
      requires_memcached: true
      rack_env: production
      force_ssl: false
      catch_and_redirect: certificate.theodi.org
      rackspace-mysql-proxy:
        database: certificates
        user: certificates
        password: how_to_security
      migrate: bundle exec rake db:migrate
      post_deploy_tasks:
      - bundle exec rake odc:deploy

  - name: staging
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-base]"
    - "recipe[mysql::client]"
    - "recipe[rackspace-mysql-proxy]"
    - "recipe[odi-users]"
    - "recipe[lib-curl]"
    - "recipe[nodejs]"
#    - "recipe[envbuilder]"
    - "recipe[memcached]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployer]"
    data_bags_path: test/data_bags
    attributes:
      user: "certificates"
      odi-ruby:
        users:
          certificates:
          - 1.9.3-p547
      envbuilder:
        base_dir: "/home/certificates"
        base_dbi: "production"
        owner: "certificates"
        group: "certificates"
      project_fqdn: "certificates.theodi.org"
      prefix: staging
      git_project: "open-data-certificate"
      databags:
        primary: "certificates"
      deployment:
        revision: "STAGING"
        precompile_assets: false
        rack_env: production
        assets_allow_origin: "*"
      database: certificates
      requires_memcached: true
      rack_env: production
      force_ssl: false
      catch_and_redirect: certificate.theodi.org
      rackspace-mysql-proxy:
        database: certificates
        user: certificates
        password: it_is_raining
      migrate: bundle exec rake db:migrate
      post_deploy_tasks:
      - bundle exec rake odc:deploy
