---
driver:
  name: rackspace
  rackspace_username: <%= ENV['RACKSPACE_USERNAME'] %>
  rackspace_api_key: <%= ENV['RACKSPACE_API_KEY'] %>
  rackspace_region: lon
  require_chef_omnibus: latest
  wait_for: 1200
  server_name: chef-odi-deployer-test

provisioner:
  name: chef_zero
  client_rb:
    environment: production

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-users]"
    - "recipe[lib-curl]"
    - "recipe[nodejs]"
    - "recipe[envbuilder]"
    - "recipe[mysql::client]"
    - "recipe[memcached]"
    - "recipe[rackspace-mysql-proxy]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployer]"
    data_bags_path: test/data_bags
    attributes:
      user: "certificates"
      odi-ruby:
        users:
          certificates:
          - 1.9.3-p547
      envbuilder:
        base_dir: "/home/certificates"
        base_dbi: "production"
        owner: "certificates"
        group: "certificates"
      project_fqdn: "certificates.theodi.org"
      git_project: "open-data-certificate"
      databags:
        primary: "certificates"
      deployment:
        revision: "testicicle"
        precompile_assets: false
        rack_env: production
        assets_allow_origin: "*"
      database: certificates
      requires_memcached: true
      rack_env: production
      force_ssl: false
      catch_and_redirect: certificate.theodi.org
      rackspace-mysql-proxy:
        database: certificates
        user: certificates
        password: how_to_security
      migrate: rake db:migrate
      post_deploy_tasks:
      - rake odc:deploy
