---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: production

platforms:
  - name: ubuntu-14.04

suites:
  - name: deployment-old-foreman
    run_list:
    - "recipe[odi-users]"
    - "recipe[odi-rvm]"
    - "recipe[envbuilder]"
    - "recipe[mysql::client]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      rvm:
        user: "deploytest"
        ruby: "1.9.3-p545"
      envbuilder:
        base_dir: "/home/deploytest"
        base_dbi: "production"
        owner: "deploytest"
        group: "deploytest"
      project_fqdn: "office-calendar.theodi.org"
      git_project: "office-calendar"
      RACK_ENV: "production"
      databags:
        primary: "office-calendar"
      deployment:
        revision: "d0a1e758c1e38edf00572c6907475eacae73f470"
  - name: deployment-new-foreman
    run_list:
    - "recipe[odi-apt]"
    - "recipe[odi-users]"
    - "recipe[lib-curl]"
    - "recipe[nodejs::install_from_package]"
    - "recipe[envbuilder]"
    - "recipe[mysql::client]"
    - "recipe[memcached]"
    - "recipe[rackspace-mysql-proxy]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "certificates"
      odi-ruby:
        users:
          certificates:
          - 1.9.3-p547
      envbuilder:
        base_dir: "/home/certificates"
        base_dbi: "production"
        owner: "certificates"
        group: "certificates"
      project_fqdn: "certificates.theodi.org"
      git_project: "open-data-certificate"
      databags:
        primary: "certificates"
      deployment:
        revision: "testicicle"
        precompile_assets: false
        rack_env: production
      database: certificates
      requires_memcached: true
      rack_env: production
      force_ssl: false
      catch_and_redirect: certificate.theodi.org
      rackspace-mysql-proxy:
        database: certificates
        user: certificates
        password: how_to_security
      migrate: rake db:migrate
      post_deploy_tasks:
      - rake odc:deploy
