---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: deployment-old-foreman
    run_list:
    - "recipe[odi-users]"
    - "recipe[odi-rvm]"
    - "recipe[envbuilder]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      rvm:
        user: "deploytest"
        ruby: "1.9.3"
      envbuilder:
        base_dir: "/home/env"
        base_dbi: "production"
        owner: "env"
        group: "env"
      project_fqdn: "deploytest.theodi.org"
      git_project: "office-calendar"
      RACK_ENV: "production"
      databags:
        primary: "deploytest"
      deployment:
        revision: "travisify"
