---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: deployment-old-foreman
    run_list:
    - "recipe[odi-users]"
    - "recipe[odi-rvm]"
    - "recipe[envbuilder]"
    - "recipe[mysql::client]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      rvm:
        user: "deploytest"
        ruby: "1.9.3"
      envbuilder:
        base_dir: "/home/deploytest"
        base_dbi: "production"
        owner: "deploytest"
        group: "deploytest"
      project_fqdn: "office-calendar.theodi.org"
      git_project: "office-calendar"
      RACK_ENV: "production"
      databags:
        primary: "office-calendar"
      deployment:
        revision: "d0a1e758c1e38edf00572c6907475eacae73f470"
  - name: deployment-new-foreman
    run_list:
    - "recipe[odi-users]"
    - "recipe[odi-rvm]"
    - "recipe[envbuilder]"
    - "recipe[mysql::client]"
    - "recipe[odi-nginx]"
    - "recipe[odi-deployment]"
    data_bags_path: test/data_bags
    attributes:
      user: "deploytest"
      rvm:
        user: "deploytest"
        ruby: "1.9.3"
      envbuilder:
        base_dir: "/home/deploytest"
        base_dbi: "production"
        owner: "deploytest"
        group: "deploytest"
      project_fqdn: "office-calendar.theodi.org"
      git_project: "office-calendar"
      databags:
        primary: "office-calendar"
      deployment:
        revision: "a8c6137279fc6d7c98c6d1b898633441e2c41ef8"
