language: ruby
rvm:
- 2.1.2
script:
- travis_wait 60 bundle exec rake
before_script:
- ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
- echo 'Host *' >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- openssl aes-256-cbc -k "$DATA_BAG_KEY" -in test/data_bags/serverdensity/credentials.enc.json -d -a -out test/data_bags/serverdensity/credentials.json
#after_success:
#- openssl enc -d -aes-256-cbc -k $CHEF_KEY -in deploy/key.enc -out deploy/key.pem
#- chmod 600 deploy/key.pem
#- bundle exec berks install
#- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bundle
#  exec rake berkshelf:upload'
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: vMT3M7ecfj1r3YFAd+EVyuae0AXQ4QHXoXWrT5o19/3+AAydYKv7R586r1VSVWblHZdjEOq2c2TNM8W0MFnJllNVudCHeR15WsFReIof2jRAFGOkwTVaixdXnhKPCqAs2wqSuYFzhv4L2Tfph/X6jOCQV0IsNE7l/eieJT13Cao=
  - secure: 05jEOV44mwz8Fg4x1ih0fxAQg3UMB4fz1jK6tp/cwsrW2dv7ARYjvv74sLOWLxfRv/Ft/KZUt2igbEQ1BuogOk7qzwbH/ChBX6iE3WY+I0v3oxMzeAJsfsMc93PMIRi+ZKR7X5v44Tp5CqMqQBk2LXDqMCXnvsdkDuppyKdMux8=
  - secure: AnXN5Ro3is9OVHKikhbSd5g1/px4Ads0EXeCPAuTcNbOWfgDRVT2EGICPWRarugPwPP+cC2hTt8UI9FSwIOtqVDVHt9b7gSYVAHGuFH61YoG5f+leexTi2nVATDJ1bzRkkKkut6g2x+bGjpUH+PX/Um9pbKaeCD6XA2yqZOgHdc=
  - secure: pxJVZVKsBx74qdef+x51m/nRsRI99vKnF+SNDsT0E7Q4yNAyy+wsxWXcz4tK1Ym8eTx6V7cyqvfh+Un3YRbSsvwB8k8X8rDtv74eaH8IXU2FpxbwUza6jNkId/vDsReP6tcVB0miUr9gBwdSU7GiDh8S+lqQ5HO0E6ugHOid+7w=
  - secure: 2V4IRvPDPjHlDeaQ9qeX3M+wFFqZTpAGbkiG/ha41LguOtHLSahbdVCvC42KPqfSzVCXTrv9XJfN+Bp3Y2SvTtoRqRFpIsuc7TFpSI2REUpUUaSS9KvdxaW9SnrT2Qj+ZPV1gYT3wB0gIra+HXI9N1rtitQo+g1cPN4vaGHaECk=
